# Generated by Django 5.0.4 on 2024-04-21 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manhwa', '0002_alter_comment_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favourites',
            old_name='Favourite',
            new_name='Favorite',
        ),
        migrations.AddField(
            model_name='favourites',
            name='started',
            field=models.DateField(null=True),
        ),
    ]
