# Generated by Django 5.0.4 on 2024-04-23 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manhwa', '0003_rename_favourite_favourites_favorite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourites',
            name='started',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
